name: Process Reporter CI

on:
  push:
    branches: [ main, master, develop ] # Adjusted branches
  pull_request:
    branches: [ main, master, develop ] # Adjusted branches

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./windows
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set Windows Execution Policy
      run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
      shell: pwsh
    - name: Install Pester (Windows)
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck -Scope CurrentUser -Confirm:$false
        Import-Module Pester -ErrorAction SilentlyContinue
      shell: pwsh
    - name: Run Pester Tests (Windows)
      run: Invoke-Pester -Path ./tests -PassThru
      shell: pwsh

  # --- ADD THE NEW MACOS JOB HERE ---
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./macos
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PowerShell Core (pwsh) on macOS
      uses: actions/setup-powershell@v1
      with:
        version: '7.x'

    - name: Display PowerShell version (macOS)
      run: pwsh -Command "$PSVersionTable"
      shell: bash

    - name: Install Pester module (macOS)
      run: |
        pwsh -Command "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted"
        pwsh -Command "Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck -Scope CurrentUser -Confirm:$false"
        pwsh -Command "Import-Module Pester -ErrorAction SilentlyContinue"
      shell: bash

    - name: Display Pester version (macOS)
      run: pwsh -Command "(Get-Module Pester -ListAvailable | Select-Object -First 1).Version.ToString()"
      shell: bash
      continue-on-error: true

    - name: Run Pester Tests (macOS)
      run: pwsh -Command "Invoke-Pester -Path ./tests -PassThru"
      shell: bash